window.SNEAKER_DATA = {
 "updatedAt": "2026-09-10 16:06",
 "sources": {
  "releases": "Sole Retriever (JSON-LD)",
  "news": [
   "Hypebeast 中文",
   "Hypebeast",
   "Nice Kicks",
   "Highsnobiety"
  ]
 },
 "unavailableFields": [
  "marketPrice 市场价：StockX/GOAT 需 API key，脚本直连被 403",
  "size 尺码范围 / channels 购买渠道：详情页被 Cloudflare 拦截",
  "得物、识货：接口需签名，无法直连"
 ],
 "brands": [
  "ADIDAS",
  "ANTA",
  "ASICS",
  "BALENCIAGA",
  "BROOKS RUNNING",
  "CELINE",
  "CLARKS",
  "CONVERSE",
  "CROCS",
  "HOKA",
  "JORDAN",
  "MIZUNO",
  "NEW BALANCE",
  "NIKE",
  "PUMA",
  "REEBOK",
  "SALOMON",
  "SAUCONY",
  "UGG",
  "VANS"
 ],
 "releases": [
  {
   "id": 64,
   "brand": "JORDAN",
   "name": "Air Jordan 9 Retro OG Space Jam",
   "sku": "IX6179-100",
   "releaseDate": "2026-09-19",
   "price": "USD 215",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/air_jordan_9_retro_og_space_jam_IX6179-100-1788732358066.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/jordan/air-jordan-9/air-jordan-9-retro-og-space-jam-ix6179-100",
   "rating": 5.0,
   "reviewCount": 65,
   "hot": 2602,
   "buzz": 714,
   "newsMentions": 0
  },
  {
   "id": 77,
   "brand": "JORDAN",
   "name": "Air Jordan 1 Retro Low OG Last Dance at the Garden",
   "sku": "IR0088-001",
   "releaseDate": "2026-09-26",
   "price": "USD 155",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/air_jordan_1_retro_low_og_last_dance_at_the_garden_IR0088-001-1788286486695.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/jordan/air-jordan-1-low/air-jordan-1-retro-low-og-last-dance-at-the-garden-ir0088-001",
   "rating": 5.0,
   "reviewCount": 57,
   "hot": 2336,
   "buzz": 603,
   "newsMentions": 0
  },
  {
   "id": 65,
   "brand": "NIKE",
   "name": "Nike Kobe 8 Protro Mambacurial",
   "sku": "IO6253-500",
   "releaseDate": "2026-09-19",
   "price": "USD 200",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/nike_kobe_8_protro_mambacurial_IO6253-500-1788898896342.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/nike/kobe-8/nike-kobe-8-protro-mambacurial-io6253-500",
   "rating": 5.0,
   "reviewCount": 39,
   "hot": 2238,
   "buzz": 558,
   "newsMentions": 0
  },
  {
   "id": 34,
   "brand": "NIKE",
   "name": "Nike SB Air Force 1 Low Yuto Horigome",
   "sku": "IO8439-100",
   "releaseDate": "2026-09-12",
   "price": "USD 125",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/nike_sb_air_force_1_low_yuto_horigome_IO8439-100-1788536144262.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/nike-sb/other/nike-sb-air-force-1-low-yuto-horigome-io8439-100",
   "rating": 5.0,
   "reviewCount": 27,
   "hot": 2224,
   "buzz": 549,
   "newsMentions": 0
  },
  {
   "id": 35,
   "brand": "NIKE",
   "name": "Nike Air Max Plus One Piece Mera Mera",
   "sku": "IW1283-800",
   "releaseDate": "2026-09-12",
   "price": "USD 180",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/nike_air_max_plus_one_piece_mera_mera_IW1283-800-1787488510047.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/nike/air-max-plus/nike-air-max-plus-one-piece-mera-mera-iw1283-800",
   "rating": 5.0,
   "reviewCount": 27,
   "hot": 2224,
   "buzz": 549,
   "newsMentions": 0
  },
  {
   "id": 66,
   "brand": "NIKE",
   "name": "Nike Air Max Plus One Piece Ope Ope",
   "sku": "IW1282-600",
   "releaseDate": "2026-09-19",
   "price": "USD 180",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/nike_air_max_plus_one_piece_ope_ope_IW1282-600-1787488694749.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/nike/air-max-plus/nike-air-max-plus-one-piece-ope-ope-iw1282-600",
   "rating": 5.0,
   "reviewCount": 29,
   "hot": 2098,
   "buzz": 498,
   "newsMentions": 0
  },
  {
   "id": 74,
   "brand": "NIKE",
   "name": "Nike Air Max Plus One Piece Gomu Gomu",
   "sku": "IR0968-500",
   "releaseDate": "2026-09-25",
   "price": "USD 180",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/nike_air_max_plus_one_piece_gomu_gomu_IR0968-500-1787488290790.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/nike/air-max-plus/nike-air-max-plus-one-piece-gomu-gomu-ir0968-500",
   "rating": 5.0,
   "reviewCount": 32,
   "hot": 2008,
   "buzz": 462,
   "newsMentions": 0
  },
  {
   "id": 78,
   "brand": "NIKE",
   "name": "Nike Air Bakin OG",
   "sku": "IQ5365-600",
   "releaseDate": "2026-09-28",
   "price": "USD 170",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/nike_air_bakin_og_IQ5365-600-1770828768985.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/nike/other/nike-air-bakin-og-iq5365-600",
   "rating": 5.0,
   "reviewCount": 26,
   "hot": 1858,
   "buzz": 399,
   "newsMentions": 0
  },
  {
   "id": 3,
   "brand": "NEW BALANCE",
   "name": "New Balance 1300 Made in USA Sea Salt Blue Oyster",
   "sku": "U1300SS",
   "releaseDate": "2026-09-10",
   "price": "USD 190",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/new_balance_1300_made_in_usa_sea_salt_blue_oyster_u1300ss-1787857151176.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/new-balance/1300/new-balance-1300-made-in-usa-sea-salt-blue-oyster-u1300ss",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 1830,
   "buzz": 605,
   "newsMentions": 2
  },
  {
   "id": 38,
   "brand": "ANTA",
   "name": "ANTA Kai 3 Alchemist",
   "sku": "8126D1102-12",
   "releaseDate": "2026-09-12",
   "price": "USD 135",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/anta_kai_3_alchemist_8126d1102-12-1788890032368.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/anta/other/anta-kai-3-alchemist-8126d1102-12",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 1786,
   "buzz": 587,
   "newsMentions": 2
  },
  {
   "id": 67,
   "brand": "ADIDAS",
   "name": "adidas Adistar Jellyfish Pharrell Williams Dark Brown Frozen Green",
   "sku": "KK2888",
   "releaseDate": "2026-09-19",
   "price": "USD 300",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/adidas_adistar_jellyfish_pharrell_williams_dark_brown_frozen_green_KK2888-1787665717026.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/adidas/pharrell-williams-adidas-adistar-jellyfish/adidas-adistar-jellyfish-pharrell-williams-dark-brown-frozen-green-kk2888",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 1632,
   "buzz": 524,
   "newsMentions": 2
  },
  {
   "id": 2,
   "brand": "VANS",
   "name": "Vans Old Skool 36 Yacht Club",
   "sku": "VN000E8VBGK",
   "releaseDate": "2026-09-10",
   "price": "USD 130",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/vans_old_skool_36_yacht_club_vn000e8vbgk-1787666233045.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/vans/old-skool/vans-old-skool-36-yacht-club-vn000e8vbgk",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 1410,
   "buzz": 505,
   "newsMentions": 1
  },
  {
   "id": 6,
   "brand": "CROCS",
   "name": "Crocs Classic Echo Clog Yu-Gi-Oh! Dark Magician",
   "sku": "213591-90H",
   "releaseDate": "2026-09-10",
   "price": "USD 70",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/crocs_classic_echo_clog_yu_gi_oh_dark_magician_213591-90H-1787694982424.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/crocs/echo/crocs-classic-echo-clog-yu-gi-oh-dark-magician-213591-90h",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 1410,
   "buzz": 505,
   "newsMentions": 1
  },
  {
   "id": 8,
   "brand": "NIKE",
   "name": "Nike Air Max Dolce Metallic Silver (W)",
   "sku": "IB4527-001",
   "releaseDate": "2026-09-10",
   "price": "USD 170",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/nike_air_max_dolce_metallic_silver_w_IB4527-001-1788188379337.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/nike/other/nike-air-max-dolce-metallic-silver-w-ib4527-001",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 1410,
   "buzz": 505,
   "newsMentions": 1
  },
  {
   "id": 9,
   "brand": "JORDAN",
   "name": "Air Jordan 3 Mid TD Metallic Silver",
   "sku": "FZ8626-002",
   "releaseDate": "2026-09-10",
   "price": "USD 205",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/air_jordan_3_mid_td_metallic_silver_FZ8626-002-1787854914651.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/jordan/nike-air-jordan-3/air-jordan-3-mid-td-metallic-silver-fz8626-002",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 1410,
   "buzz": 505,
   "newsMentions": 1
  },
  {
   "id": 10,
   "brand": "ADIDAS",
   "name": "adidas Taekwondo Ballerina Simone Rocha Core Black (W)",
   "sku": "KJ5248",
   "releaseDate": "2026-09-10",
   "price": "USD 250",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/adidas_taekwondo_ballerina_simone_rocha_core_black_w_KJ5248-1788445749546.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/adidas/taekwondo/adidas-taekwondo-ballerina-simone-rocha-core-black-w-kj5248",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 1410,
   "buzz": 505,
   "newsMentions": 1
  },
  {
   "id": 11,
   "brand": "ADIDAS",
   "name": "adidas Japan Slip-On Simone Rocha Magic Beige (W)",
   "sku": "KJ5251",
   "releaseDate": "2026-09-10",
   "price": "USD 220",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/adidas_japan_slip_on_simone_rocha_magic_beige_w_KJ5251-1788446523522.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/adidas/other/adidas-japan-slip-on-simone-rocha-magic-beige-w-kj5251",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 1410,
   "buzz": 505,
   "newsMentions": 1
  },
  {
   "id": 13,
   "brand": "ADIDAS",
   "name": "adidas Climacool Simone Rocha Core Black (W)",
   "sku": "KH7452",
   "releaseDate": "2026-09-10",
   "price": "USD 250",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/adidas_climacool_simone_rocha_core_black_w_KH7452-1788446101525.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/adidas/other/adidas-climacool-simone-rocha-core-black-w-kh7452",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 1410,
   "buzz": 505,
   "newsMentions": 1
  },
  {
   "id": 14,
   "brand": "ADIDAS",
   "name": "adidas Japan Slip-On Simone Rocha Core Black (W)",
   "sku": "KH7275",
   "releaseDate": "2026-09-10",
   "price": "USD 220",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/adidas_japan_slip_on_simone_rocha_core_black_w_KH7275-1788446976683.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/adidas/other/adidas-japan-slip-on-simone-rocha-core-black-w-kh7275",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 1410,
   "buzz": 505,
   "newsMentions": 1
  },
  {
   "id": 19,
   "brand": "ADIDAS",
   "name": "adidas Taekwondo Ballerina Simone Rocha Pink Tint (W)",
   "sku": "KJ5249",
   "releaseDate": "2026-09-10",
   "price": "USD 250",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/adidas_taekwondo_ballerina_simone_rocha_pink_tint_w_KJ5249-1788445482622.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/adidas/taekwondo/adidas-taekwondo-ballerina-simone-rocha-pink-tint-w-kj5249",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 1410,
   "buzz": 505,
   "newsMentions": 1
  },
  {
   "id": 27,
   "brand": "NIKE",
   "name": "Nike Air Rift 2 Black Metallic Silver (W)",
   "sku": "IQ8006-003",
   "releaseDate": "2026-09-10",
   "price": "USD 125",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/nike_air_rift_2_black_metallic_silver_w_IQ8006-003-1788371461793.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/nike/other/nike-air-rift-2-black-metallic-silver-w-iq8006-003",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 1410,
   "buzz": 505,
   "newsMentions": 1
  },
  {
   "id": 42,
   "brand": "ASICS",
   "name": "Asics Gel-Kinetic FR Cecilie Bahnsen Piedmont Grey",
   "sku": "1203B171-020",
   "releaseDate": "2026-09-12",
   "price": "USD 200",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/asics_gel_kinetic_fr_cecilie_bahnsen_piedmont_grey_1203B171-020-1787692540012.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/asics/other/asics-gel-kinetic-fr-cecilie-bahnsen-piedmont-grey-1203b171-020",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 1366,
   "buzz": 487,
   "newsMentions": 1
  },
  {
   "id": 48,
   "brand": "NIKE",
   "name": "Nike First Sight Shadow Light Crimson (W)",
   "sku": "HQ2410-600",
   "releaseDate": "2026-09-15",
   "price": "USD 145",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/nike_first_sight_shadow_light_crimson_w_HQ2410-600-1787236554629.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/nike/other/nike-first-sight-shadow-light-crimson-w-hq2410-600",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 1300,
   "buzz": 460,
   "newsMentions": 1
  },
  {
   "id": 49,
   "brand": "NIKE",
   "name": "Nike First Sight Mirage Light Crimson (W)",
   "sku": "HQ2412-600",
   "releaseDate": "2026-09-15",
   "price": "USD 170",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/nike_first_sight_mirage_light_crimson_w_HQ2412-600-1788366450553.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/nike/other/nike-first-sight-mirage-light-crimson-w-hq2412-600",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 1300,
   "buzz": 460,
   "newsMentions": 1
  },
  {
   "id": 58,
   "brand": "VANS",
   "name": "Vans Old Skool 36 K-Pop Demon Hunters Rumi (GS)",
   "sku": "VN000ECUYLW",
   "releaseDate": "2026-09-18",
   "price": "USD 75",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/vans_old_skool_36_k-pop_demon_hunters_rumi_gs_vn000ecuylw-1788624575178.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/vans/old-skool/vans-old-skool-36-k-pop-demon-hunters-rumi-gs-vn000ecuylw",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 1234,
   "buzz": 433,
   "newsMentions": 1
  },
  {
   "id": 63,
   "brand": "NIKE",
   "name": "Nike KD 6 PSG Metallic Silver",
   "sku": "IU0593-001",
   "releaseDate": "2026-09-18",
   "price": "USD 135",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/Untitled%20design%20-%202026-09-02T162702689-1788380846471.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/nike/kd-6/nike-kd-6-psg-metallic-silver-iu0593-001",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 1234,
   "buzz": 433,
   "newsMentions": 1
  },
  {
   "id": 69,
   "brand": "NIKE",
   "name": "Nike GT Future Varsity Red",
   "sku": "FZ5590-603",
   "releaseDate": "2026-09-22",
   "price": "USD 210",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/Untitled%20design%20-%202026-07-21T180625210-1784671593453.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/nike/nike-gt-future/nike-gt-future-varsity-red-fz5590-603",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 1146,
   "buzz": 397,
   "newsMentions": 1
  },
  {
   "id": 75,
   "brand": "PUMA",
   "name": "Puma MB.06 Shooting Star",
   "sku": "313624-01",
   "releaseDate": "2026-09-25",
   "price": "USD 130",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/puma_mb_06_shooting_star_313624-01-1787597403777.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/puma/other/puma-mb-06-shooting-star-313624-01",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 1080,
   "buzz": 370,
   "newsMentions": 1
  },
  {
   "id": 80,
   "brand": "NIKE",
   "name": "Nike Air Zoom Hyperslide Hyperice Orewood Brown",
   "sku": "66005-001",
   "releaseDate": "2026-09-29",
   "price": "USD 249",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/nike_air_zoom_hyperslide_hyperice_orewood_brown_66005-001-1787668378041.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/nike/other/nike-air-zoom-hyperslide-hyperice-orewood-brown-66005-001",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 992,
   "buzz": 334,
   "newsMentions": 1
  },
  {
   "id": 1,
   "brand": "NIKE",
   "name": "Nike Air Zoom Huarache 2K4 Penny Hardaway",
   "sku": "IV0345-001",
   "releaseDate": "2026-09-10",
   "price": "USD 200",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/nike_air_zoom_huarache_2k4_penny_hardaway_IV0345-001-1787413757062.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/nike/air-huarache/nike-air-zoom-huarache-2k4-penny-hardaway-iv0345-001",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 990,
   "buzz": 405,
   "newsMentions": 0
  },
  {
   "id": 4,
   "brand": "CROCS",
   "name": "Crocs Echo Clog Yu-Gi-Oh! Blue-Eyes White Dragon",
   "sku": "213732-90H",
   "releaseDate": "2026-09-10",
   "price": "USD 90",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/crocs_echo_clog_yu_gi_oh_blue_eyes_white_dragon_213732-90H-1787695313022.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/crocs/echo/crocs-echo-clog-yu-gi-oh-blue-eyes-white-dragon-213732-90h",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 990,
   "buzz": 405,
   "newsMentions": 0
  },
  {
   "id": 5,
   "brand": "NIKE",
   "name": "Nike Book 2 Penny Chevy",
   "sku": "IO9841-900",
   "releaseDate": "2026-09-10",
   "price": "USD 155",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/Untitled%20design%20-%202026-08-13T101434209-1786630481149.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/nike/nike-book-2/nike-book-2-penny-chevy-io9841-900",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 990,
   "buzz": 405,
   "newsMentions": 0
  },
  {
   "id": 7,
   "brand": "UGG",
   "name": "UGG Otzo Clog Willy Chavarria",
   "sku": "1188190-BLK",
   "releaseDate": "2026-09-10",
   "price": "USD 250",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/ugg_otzo_clog_willy_chavarria_1188190-BLK-1788478426870.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/ugg/other/ugg-otzo-clog-willy-chavarria-1188190-blk",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 990,
   "buzz": 405,
   "newsMentions": 0
  },
  {
   "id": 12,
   "brand": "REEBOK",
   "name": "Reebok Brutus Low Heritage Green",
   "sku": "100263449",
   "releaseDate": "2026-09-10",
   "price": "USD 130",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/reebok_brutus_low_heritage_green_100263449-1788611096087.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/reebok/other/reebok-brutus-low-heritage-green-100263449",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 990,
   "buzz": 405,
   "newsMentions": 0
  },
  {
   "id": 15,
   "brand": "CROCS",
   "name": "Crocs Classic Clog Yu-Gi-Oh! Yugi Yami",
   "sku": "213589-90H",
   "releaseDate": "2026-09-10",
   "price": "USD 70",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/Untitled%20design%20-%202026-09-01T131923458-1788283170796.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/crocs/classic-clog/crocs-classic-clog-yu-gi-oh-yugi-yami-213589-90h",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 990,
   "buzz": 405,
   "newsMentions": 0
  },
  {
   "id": 16,
   "brand": "VANS",
   "name": "Vans LX Classic Slip-On 98 Act of Disagreement",
   "sku": "VN00111F95Y1",
   "releaseDate": "2026-09-10",
   "price": "USD 90",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/vans_lx_classic_slip_on_98_act_of_disagreement_vn00111f95y1-1788874134734.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/vans/slip-on/vans-lx-classic-slip-on-98-act-of-disagreement-vn00111f95y1",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 990,
   "buzz": 405,
   "newsMentions": 0
  },
  {
   "id": 17,
   "brand": "CROCS",
   "name": "Crocs Classic Classic Clog Yu-Gi-Oh! Seto Kaiba",
   "sku": "213590-90H",
   "releaseDate": "2026-09-10",
   "price": "USD 90",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/Untitled%20design%20-%202026-09-01T131714882-1788283048363.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/crocs/classic-clog/crocs-classic-classic-clog-yu-gi-oh-seto-kaiba-213590-90h",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 990,
   "buzz": 405,
   "newsMentions": 0
  },
  {
   "id": 18,
   "brand": "SALOMON",
   "name": "Salomon XT-4 OG Tacos Domingo",
   "sku": "L45487300",
   "releaseDate": "2026-09-10",
   "price": "USD 200",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/salomon_xt_4_og_tacos_domingo_l45487300-1788963373775.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/salomon/other/salomon-xt-4-og-tacos-domingo-l45487300",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 990,
   "buzz": 405,
   "newsMentions": 0
  },
  {
   "id": 20,
   "brand": "BROOKS RUNNING",
   "name": "Brooks Ghost Trail Alex Zono Simmental Brown",
   "sku": "1000691D224",
   "releaseDate": "2026-09-10",
   "price": "USD 175",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/brooks_ghost_trail_alex_zono_simmental_brown_1000691D224-1788986518180.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/brooks-running/other/brooks-ghost-trail-alex-zono-simmental-brown-1000691d224",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 990,
   "buzz": 405,
   "newsMentions": 0
  },
  {
   "id": 21,
   "brand": "BROOKS RUNNING",
   "name": "Brooks Ghost Trail Alex Zono Poppy Red",
   "sku": "1000691D681",
   "releaseDate": "2026-09-10",
   "price": "USD 162",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/brooks_ghost_trail_alex_zono_poppy_red_1000691D681-1788986724970.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/brooks-running/other/brooks-ghost-trail-alex-zono-poppy-red-1000691d681",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 990,
   "buzz": 405,
   "newsMentions": 0
  },
  {
   "id": 22,
   "brand": "PUMA",
   "name": "Puma Deviate NITRO 4 Brightstride",
   "sku": "313698-01",
   "releaseDate": "2026-09-10",
   "price": "USD 170",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/puma_deviate_nitro_4_brightstride_313698-01-1788988942421.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/puma/other/puma-deviate-nitro-4-brightstride-313698-01",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 990,
   "buzz": 405,
   "newsMentions": 0
  },
  {
   "id": 23,
   "brand": "PUMA",
   "name": "Puma Deviate NITRO 4 Sunny Slime",
   "sku": "312123-27",
   "releaseDate": "2026-09-10",
   "price": "USD 170",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/puma_deviate_nitro_4_sunny_slime_312123-27-1788988961336.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/puma/other/puma-deviate-nitro-4-sunny-slime-312123-27",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 990,
   "buzz": 405,
   "newsMentions": 0
  },
  {
   "id": 24,
   "brand": "PUMA",
   "name": "Puma Deviate Pure NITRO Sunny Lime",
   "sku": "313904-13",
   "releaseDate": "2026-09-10",
   "price": "USD 150",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/puma_deviate_pure_nitro_sunny_lime_313904-13-1788990521186.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/puma/other/puma-deviate-pure-nitro-sunny-lime-313904-13",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 990,
   "buzz": 405,
   "newsMentions": 0
  },
  {
   "id": 25,
   "brand": "PUMA",
   "name": "Puma Velocity NITRO 5 Sunny Lime",
   "sku": "312944-10",
   "releaseDate": "2026-09-10",
   "price": "USD 140",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/puma_velocity_nitro_5_sunny_lime_312944-10-1788989738348.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/puma/other/puma-velocity-nitro-5-sunny-lime-312944-10",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 990,
   "buzz": 405,
   "newsMentions": 0
  },
  {
   "id": 26,
   "brand": "PUMA",
   "name": "Puma Deviate NITRO 4 Brightstride (W)",
   "sku": "313699-01",
   "releaseDate": "2026-09-10",
   "price": "USD 170",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/puma_deviate_nitro_4_brightstride_w_313699-01-1788990489442.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/puma/other/puma-deviate-nitro-4-brightstride-w-313699-01",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 990,
   "buzz": 405,
   "newsMentions": 0
  },
  {
   "id": 28,
   "brand": "UGG",
   "name": "UGG Guard Boot Willy Chavarria",
   "sku": "1186774-BLK",
   "releaseDate": "2026-09-10",
   "price": "USD 800",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/ugg_guard_boot_willy_chavarria_1186774-BLK-1788477325525.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/ugg/other/ugg-guard-boot-willy-chavarria-1186774-blk",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 990,
   "buzz": 405,
   "newsMentions": 0
  },
  {
   "id": 29,
   "brand": "UGG",
   "name": "UGG Biker Boot Willy Chavarria",
   "sku": "1186775-BLK",
   "releaseDate": "2026-09-10",
   "price": "USD 500",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/ugg_biker_boot_willy_chavarria_1186775-BLK-1788477655852.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/ugg/other/ugg-biker-boot-willy-chavarria-1186775-blk",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 990,
   "buzz": 405,
   "newsMentions": 0
  },
  {
   "id": 30,
   "brand": "UGG",
   "name": "UGG Hotel Slipper Willy Chavarria",
   "sku": "1186777-BLK",
   "releaseDate": "2026-09-10",
   "price": "USD 190",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/ugg_hotel_slipper_willy_chavarria_1186777-BLK-1788477896529.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/ugg/other/ugg-hotel-slipper-willy-chavarria-1186777-blk",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 990,
   "buzz": 405,
   "newsMentions": 0
  },
  {
   "id": 31,
   "brand": "UGG",
   "name": "UGG Relaxed Boot Willy Chavarria",
   "sku": "1186776-BLK",
   "releaseDate": "2026-09-10",
   "price": "USD 450",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/ugg_relaxed_boot_willy_chavarria_1186776-BLK-1788478077232.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/ugg/other/ugg-relaxed-boot-willy-chavarria-1186776-blk",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 990,
   "buzz": 405,
   "newsMentions": 0
  },
  {
   "id": 32,
   "brand": "ADIDAS",
   "name": "adidas Handball Spezial Sneaker Politics Rhythm & Blues",
   "sku": "KZ6656",
   "releaseDate": "2026-09-11",
   "price": "USD 110",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/adidas_handball_spezial_sneaker_politics_rhythm_blues_KZ6656-1788790524935.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/adidas/spezial/adidas-handball-spezial-sneaker-politics-rhythm-blues-kz6656",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 968,
   "buzz": 396,
   "newsMentions": 0
  },
  {
   "id": 33,
   "brand": "NIKE",
   "name": "Nike Vomero Premium Black White (W)",
   "sku": "IU2827-001",
   "releaseDate": "2026-09-11",
   "price": "USD 230",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/nike_vomero_premium_black_white_w_IU2827-001-1787939397670.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/nike/nike-vomero/nike-vomero-premium-black-white-w-iu2827-001",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 968,
   "buzz": 396,
   "newsMentions": 0
  },
  {
   "id": 36,
   "brand": "JORDAN",
   "name": "Air Jordan 4 Retro London",
   "sku": "IV6048-001",
   "releaseDate": "2026-09-12",
   "price": "USD 230",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/Untitled%20design%20-%202026-08-27T111857086-1787843943600.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/jordan/nike-air-jordan-4/air-jordan-4-retro-london-iv6048-001",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 946,
   "buzz": 387,
   "newsMentions": 0
  },
  {
   "id": 37,
   "brand": "JORDAN",
   "name": "Air Jordan 12 Retro Idols Become Rivals",
   "sku": "CT8013-103",
   "releaseDate": "2026-09-12",
   "price": "USD 215",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/air_jordan_12_retro_bucks_CT8013-103-1788026696696.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/jordan/air-jordan-12/air-jordan-12-retro-bucks-ct8013-103",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 946,
   "buzz": 387,
   "newsMentions": 0
  },
  {
   "id": 39,
   "brand": "NIKE",
   "name": "Nike Air Max 90 Wagyu Black",
   "sku": "IR1979-010",
   "releaseDate": "2026-09-12",
   "price": "USD 150",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/Untitled%20design%20-%202026-09-02T124110049-1788367279968.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/nike/nike-air-max-90/nike-air-max-90-wagyu-black-ir1979-010",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 946,
   "buzz": 387,
   "newsMentions": 0
  },
  {
   "id": 40,
   "brand": "PUMA",
   "name": "Puma Suede Street Fighter Ken Masters",
   "sku": "410646-01",
   "releaseDate": "2026-09-12",
   "price": "USD 100",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/puma_suede_street_fighter_ken_masters_410646-01-1787062293884.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/puma/other/puma-suede-street-fighter-ken-masters-410646-01",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 946,
   "buzz": 387,
   "newsMentions": 0
  },
  {
   "id": 41,
   "brand": "PUMA",
   "name": "Puma Suede Street Fighter Ryu",
   "sku": "410647-01",
   "releaseDate": "2026-09-12",
   "price": "USD 100",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/puma_suede_street_fighter_ryu_410647-01-1787062135726.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/puma/other/puma-suede-street-fighter-ryu-410647-01",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 946,
   "buzz": 387,
   "newsMentions": 0
  },
  {
   "id": 43,
   "brand": "ADIDAS",
   "name": "adidas Samba Espadrille CLOT Core Black",
   "sku": "KI4323",
   "releaseDate": "2026-09-12",
   "price": "USD 140",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/adidas_samba_espadrille_clot_core_black_KI4323-1788877275289.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/adidas/samba/adidas-samba-espadrille-clot-core-black-ki4323",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 946,
   "buzz": 387,
   "newsMentions": 0
  },
  {
   "id": 44,
   "brand": "ADIDAS",
   "name": "adidas Samba Espadrille CLOT Court Green",
   "sku": "KI4326",
   "releaseDate": "2026-09-12",
   "price": "USD 140",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/adidas_samba_espadrille_clot_court_green_KI4326-1788877568412.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/adidas/samba/adidas-samba-espadrille-clot-court-green-ki4326",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 946,
   "buzz": 387,
   "newsMentions": 0
  },
  {
   "id": 45,
   "brand": "ADIDAS",
   "name": "adidas München BSTN Oktoberfest",
   "sku": "LA3456",
   "releaseDate": "2026-09-12",
   "price": "USD 154",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/adidas_munchen_bstn_oktoberfest_LA3456-1788963632210.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/adidas/other/adidas-munchen-bstn-oktoberfest-la3456",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 946,
   "buzz": 387,
   "newsMentions": 0
  },
  {
   "id": 46,
   "brand": "ASICS",
   "name": "Asics Gel-Kinetic FR Cecilie Bahnsen Black Coffee",
   "sku": "1203B171-001",
   "releaseDate": "2026-09-12",
   "price": "USD 200",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/asics_gel_kinetic_fr_cecilie_bahnsen_black_coffee_1203B171-001-1787692328834.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/asics/other/asics-gel-kinetic-fr-cecilie-bahnsen-black-coffee-1203b171-001",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 946,
   "buzz": 387,
   "newsMentions": 0
  },
  {
   "id": 47,
   "brand": "ADIDAS",
   "name": "adidas BadBo 1.1 Bad Bunny Chalk White",
   "sku": "LC5466",
   "releaseDate": "2026-09-15",
   "price": "USD 120",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/adidas_badbo_1_1_bad_bunny_chalk_white_LC5466-1788183497282.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/adidas/other/adidas-badbo-1-1-bad-bunny-chalk-white-lc5466",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 880,
   "buzz": 360,
   "newsMentions": 0
  },
  {
   "id": 50,
   "brand": "CROCS",
   "name": "Crocs Quick Trail Racer Currant",
   "sku": "212713-7DW",
   "releaseDate": "2026-09-15",
   "price": "USD 110",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/crocs-quick-trail-racer-currant-212713-7dw.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/crocs/other/crocs-quick-trail-racer-currant-212713-7dw",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 880,
   "buzz": 360,
   "newsMentions": 0
  },
  {
   "id": 51,
   "brand": "ADIDAS",
   "name": "adidas AE 3 Bliss Blue",
   "sku": "KH8537",
   "releaseDate": "2026-09-15",
   "price": "USD 130",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/Untitled%20design%20-%202026-08-19T093144993-1787146311218.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/adidas/other/adidas-ae-3-bliss-blue-kh8537",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 880,
   "buzz": 360,
   "newsMentions": 0
  },
  {
   "id": 52,
   "brand": "CROCS",
   "name": "Crocs Lightning McQueen Cars Dinoco",
   "sku": "213582-90H",
   "releaseDate": "2026-09-16",
   "price": "USD 80",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/crocs_lightning_mcqueen_cars_dinoco_213582-90h-1786551769361.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/crocs/other/crocs-lightning-mcqueen-cars-dinoco-213582-90h",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 858,
   "buzz": 351,
   "newsMentions": 0
  },
  {
   "id": 53,
   "brand": "JORDAN",
   "name": "Air Jordan 6 Retro Low Desert Berry (W)",
   "sku": "IX5195-001",
   "releaseDate": "2026-09-16",
   "price": "USD 205",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/air_jordan_6_retro_low_desert_berry_w_IX5195-001-1787413494968.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/jordan/air-jordan-6/air-jordan-6-retro-low-desert-berry-w-ix5195-001",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 858,
   "buzz": 351,
   "newsMentions": 0
  },
  {
   "id": 54,
   "brand": "NEW BALANCE",
   "name": "New Balance 1890A Cowprint",
   "sku": "U18906M2",
   "releaseDate": "2026-09-16",
   "price": "USD 190",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/new_balance_1890a_cowprint_U18906M2-1786738048037.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/new-balance/1890/new-balance-1890a-cowprint-u18906m2",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 858,
   "buzz": 351,
   "newsMentions": 0
  },
  {
   "id": 55,
   "brand": "NIKE",
   "name": "Nike Air Foamposite Pro Camo",
   "sku": "IM5204-001",
   "releaseDate": "2026-09-18",
   "price": "USD 260",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/nike_air_foamposite_pro_camo_IM5204-001-1788659521795.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/nike/foamposite/nike-air-foamposite-pro-camo-im5204-001",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 814,
   "buzz": 333,
   "newsMentions": 0
  },
  {
   "id": 56,
   "brand": "NIKE",
   "name": "Nike Ja 4 Jaws",
   "sku": "JA9742-400",
   "releaseDate": "2026-09-18",
   "price": "USD 140",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/Untitled%20design%20-%202026-09-08T114317952-1788882211476.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/nike/ja-4/nike-ja-4-jaws-ja9742-400",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 814,
   "buzz": 333,
   "newsMentions": 0
  },
  {
   "id": 57,
   "brand": "NIKE",
   "name": "Nike A'Two Dawn Staley PE",
   "sku": "IX1923-100",
   "releaseDate": "2026-09-18",
   "price": "USD 145",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/Untitled%20design%20-%202026-08-24T161859620-1787602753893.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/nike/a-two/nike-a-two-dawn-staley-pe-ix1923-100",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 814,
   "buzz": 333,
   "newsMentions": 0
  },
  {
   "id": 59,
   "brand": "VANS",
   "name": "Vans Authentic Hi K-Pop Demon Hunters Mira (GS)",
   "sku": "VN000V93BLK",
   "releaseDate": "2026-09-18",
   "price": "USD 75",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/vans_authentic_hi_k_pop_demon_hunters_mira_gs_vn000v93blk-1788625983506.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/vans/vans-authentic/vans-authentic-hi-k-pop-demon-hunters-mira-gs-vn000v93blk",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 814,
   "buzz": 333,
   "newsMentions": 0
  },
  {
   "id": 60,
   "brand": "VANS",
   "name": "Vans Classic Slip-On K-Pop Demon Hunters Zoey (GS)",
   "sku": "VN000EC3CJE",
   "releaseDate": "2026-09-18",
   "price": "USD 65",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/vans_classic_slip_on_k_pop_demon_hunters_zoey_gs_vn000ec3cje-1788626318717.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/vans/slip-on/vans-classic-slip-on-k-pop-demon-hunters-zoey-gs-vn000ec3cje",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 814,
   "buzz": 333,
   "newsMentions": 0
  },
  {
   "id": 61,
   "brand": "VANS",
   "name": "Vans Classic Slip-On K-Pop Demon Hunters Derpy (GS)",
   "sku": "VN000ED2CJF",
   "releaseDate": "2026-09-18",
   "price": "USD 75",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/vans_classic_slip_on_k_pop_demon_hunters_derpy_gs_vn000ed2cjf-1788627195191.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/vans/slip-on/vans-classic-slip-on-k-pop-demon-hunters-derpy-gs-vn000ed2cjf",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 814,
   "buzz": 333,
   "newsMentions": 0
  },
  {
   "id": 62,
   "brand": "NIKE",
   "name": "Nike LeBron 23 Laser PE",
   "sku": "IM5125-100",
   "releaseDate": "2026-09-18",
   "price": "USD 210",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/nike_lebron_23_laser_pe_IM5125-100-1788812927700.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/nike/nike-lebron-23/nike-lebron-23-laser-pe-im5125-100",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 814,
   "buzz": 333,
   "newsMentions": 0
  },
  {
   "id": 68,
   "brand": "SAUCONY",
   "name": "Saucony ProGrid Guide 7 Stan Birch",
   "sku": "S71070-2",
   "releaseDate": "2026-09-21",
   "price": "USD 165",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/Untitled%20design%20-%202026-09-03T092116549-1788441726667.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/saucony/other/saucony-progrid-guide-7-stan-birch-s71070-2",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 748,
   "buzz": 306,
   "newsMentions": 0
  },
  {
   "id": 70,
   "brand": "CROCS",
   "name": "Crocs Classic Clog Halloween",
   "sku": "213831-90H",
   "releaseDate": "2026-09-24",
   "price": "USD 70",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/crocs_classic_clog_halloween_213831-90h-1788462659044.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/crocs/classic-clog/crocs-classic-clog-halloween-213831-90h",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 682,
   "buzz": 279,
   "newsMentions": 0
  },
  {
   "id": 71,
   "brand": "CROCS",
   "name": "Crocs Classic Clog Saw",
   "sku": "213832-90H",
   "releaseDate": "2026-09-24",
   "price": "USD 70",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/crocs_classic_clog_saw_213832-90h-1788462822194.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/crocs/classic-clog/crocs-classic-clog-saw-213832-90h",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 682,
   "buzz": 279,
   "newsMentions": 0
  },
  {
   "id": 72,
   "brand": "CONVERSE",
   "name": "Converse Shai 001 Ghosted Dream Yellow",
   "sku": "A23976C",
   "releaseDate": "2026-09-24",
   "price": "USD 140",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/converse_shai_001_ghosted_dream_yellow_a23976c-1787667024399.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/converse/shai-001/converse-shai-001-ghosted-dream-yellow-a23976c",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 682,
   "buzz": 279,
   "newsMentions": 0
  },
  {
   "id": 73,
   "brand": "CONVERSE",
   "name": "Converse Shai 001 Shock",
   "sku": "A23975C",
   "releaseDate": "2026-09-24",
   "price": "USD 140",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/converse_shai_001_shock_a23975c-1788962855688.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/converse/shai-001/converse-shai-001-shock-a23975c",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 682,
   "buzz": 279,
   "newsMentions": 0
  },
  {
   "id": 76,
   "brand": "REEBOK",
   "name": "Reebok Club C 85 BBC Grey",
   "sku": "100285332",
   "releaseDate": "2026-09-25",
   "price": "USD 120",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/reebok_club_c_85_bbc_grey_100285332-1788959085288.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/reebok/club-c/reebok-club-c-85-bbc-grey-100285332",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 660,
   "buzz": 270,
   "newsMentions": 0
  },
  {
   "id": 79,
   "brand": "NIKE",
   "name": "Nike Air Zoom Hyperslide Hyperice Black",
   "sku": "66000-001",
   "releaseDate": "2026-09-29",
   "price": "USD 249",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/nike_air_zoom_hyperslide_hyperice_black_66000-001-1787668120730.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/nike/other/nike-air-zoom-hyperslide-hyperice-black-66000-001",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 572,
   "buzz": 234,
   "newsMentions": 0
  },
  {
   "id": 81,
   "brand": "REEBOK",
   "name": "Reebok Club C Revenge Golf Manors Vintage Chalk Espresso",
   "sku": "100284837",
   "releaseDate": "2026-09-30",
   "price": "USD 130",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/reebok_club_c_revenge_golf_manors_vintage_chalk_100284837-1786996924624.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/reebok/club-c/reebok-club-c-revenge-golf-manors-vintage-chalk-100284837",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 550,
   "buzz": 225,
   "newsMentions": 0
  },
  {
   "id": 82,
   "brand": "REEBOK",
   "name": "Reebok Club C Revenge Golf Manors Vintage Chalk Legacy Green",
   "sku": "100284838",
   "releaseDate": "2026-09-30",
   "price": "USD 130",
   "marketPrice": "—",
   "size": "—",
   "collab": "—",
   "channels": [],
   "image": "https://images.soleretriever.com/sb/products/reebok_club_c_revenge_golf_manors_vintage_chalk_legacy_green_100284838-1786997086797.webp",
   "url": "https://www.soleretriever.com/sneaker-release-dates/reebok/club-c/reebok-club-c-revenge-golf-manors-vintage-chalk-legacy-green-100284838",
   "rating": 0.0,
   "reviewCount": 0,
   "hot": 550,
   "buzz": 225,
   "newsMentions": 0
  }
 ],
 "news": [
  {
   "id": 1,
   "title": "Clarks Walla Eden GTX「Black」以全粒面皮革及 GTX 防護從容應對雨天",
   "source": "Hypebeast 中文",
   "date": "2026-09-10",
   "content": "名稱： Clarks Originals Walla Eden GTX配色： 黑色產品編號： CLM27893R建議零售價： 7,880 新台幣（約 250 美元），全球售價待定發售日期： 現已於台灣發售，全球發售日期待定購買地點： Clarks TaiwanClarks 為 2026 年秋冬系列加入 Walla Eden GTX；這雙運動休閒鞋專為應對季節裡較潮濕的日子而設。鞋款歸入品牌 ORIGINALs Classic Series，以經過驗證的材質為主，而非大幅改造設計；在著重機能之餘，仍保留品牌熟悉的輪廓。Walla Eden GTX 的核心在於真皮鞋身。這種材質兼顧耐用度，鞋面亦保有足夠柔韌性，適合日常穿著。皮革基底再加入 GTX 防水技術，形成抵禦雨水及積水的屏障，是多數休閒運動鞋難以具備的防護。這個組合為 Walla Eden GTX 定下明確定位：它是一雙具防水性能的運動休閒鞋，可在雨天通勤與日常造型之間靈活切換，無須特意換上專用雨靴。黑色配色亦讓鞋款更百搭，焦點落在皮革與 GTX 細節之上，而非搶眼的季節性圖案。這款鞋被納入 Clarks Originals Classic Series，意味它並非一次性的實驗之作，而是為品牌長年沿用於休閒鞋履的經典脈絡作出機能更新，並加上適合 2026 年秋冬推出時節的防風雨性能。 Click here to view full gallery at Hypebeast",
   "image": "https://image-cdn.hypb.st/https%3A%2F%2Fhk.hypebeast.com%2Ffiles%2F2026%2F09%2FftClarks-Originals-Walla-Eden-GTX-Black-CLM27893R-Official-Images-Taiwan-Release-Info.jpg?w=800&cbr=1&q=90&fit=max",
   "link": "https://hypebeast.com/zh/2026/9/clarks-originals-walla-eden-gtx-black-clm27893r-official-images-taiwan-release-info",
   "lang": "zh",
   "relatedBrands": [
    "CLARKS"
   ]
  },
  {
   "id": 2,
   "title": "東京時裝週 SS27 鞋履趨勢：前衛厚底樂福鞋、機能越野跑鞋與經典足球鞋款",
   "source": "Hypebeast 中文",
   "date": "2026-09-10",
   "content": "摘要 Tokyo Fashion Week SS27 街頭造型呈現出多元豐富的鞋履風格，從 technical 跑鞋輪廓到奢華剪裁與前衛設計一應俱全。當中焦點包括多個高話題聯乘企劃，以及來自 Doublet、MIKIOSAKABE 和 Comme des Garçons x Salomon 的多重質感鞋款。整體鞋履陣容圍繞混合設計展開，橫跨室內足球訓練鞋、厚重平台大底到覆有金屬鉚釘的帆布鞋身。 2027 春夏東京時裝週的鞋履，呈現機能性能、復古室內運動元素與前衛實驗設計交錯並存的豐富面貌。日本首都的街頭上，觀秀者以機能跑鞋、概念感十足的厚底鞋，以及俐落的低筒鞋款，為整體造型奠定基調。跑鞋與越野鞋輪廓在街頭依然佔據一席之地。機能鞋款焦點包括「Wolf Grey」配色的 Nike Air Max Plus Tiempo 混合鞋款、Mizuno Wave Prophecy 1「Harbor Mist/Chinese Red/Black」配色，以及戰術風格的 Salomon XA Forces 8 GTX EN。聯乘跑鞋亦相當突出，例如 Awake NY x ASICS Gel Preleus「Cool Grey Silver」配色、AURALEE x New Balance 990v4 低調的「Dusty Blue」配色；此外還有 New Balance 2002R、ASICS GEL-Cumulus 16「Cinnamon/Pure Silver」配色、HOKA Speedgoat 2 TS 及 Satisfy TheROCKER 等常規鞋款。雕塑感與吸睛設計則為整體陣容注入實驗氣息。焦點鞋款包括 grounds Jewelry Loafer「Enamel Blood」配色、MIKIOSAKABE「Jewelry」Ark Whale、黑色厚底 Comme des Garçons x Salomon XT-Whisper Void，以及 Doublet 綠色 Dirty Spike Toe Cap Canvas Sneakers；後者採用仿舊鞋面，並綴以橡膠尖刺。低筒球場鞋與",
   "image": "https://image-cdn.hypb.st/https%3A%2F%2Fhk.hypebeast.com%2Ffiles%2F2026%2F09%2Fbest-footwear-trends-tokyo-fashion-week-ss27-000.jpg?w=800&cbr=1&q=90&fit=max",
   "link": "https://hypebeast.com/zh/2026/9/best-footwear-trends-tokyo-fashion-week-ss27",
   "lang": "zh",
   "relatedBrands": [
    "ADIDAS",
    "ASICS",
    "BALENCIAGA",
    "HOKA",
    "MIZUNO",
    "NEW BALANCE",
    "NIKE",
    "PUMA",
    "SALOMON"
   ]
  },
  {
   "id": 3,
   "title": "Clarks Walla Eden GTX “Black” Shrugs Off Rain With Full-Grain Leather and GTX Protection",
   "source": "Hypebeast",
   "date": "2026-09-10",
   "content": "Name: Clarks Originals Walla Eden GTXColorway: BlackSKU: CLM27893RMSRP: $7,880 NTD (approx. $250 USD), TBC (Global)Release Date: Available now (Taiwan), TBC (Global)Where to Buy: Clarks TaiwanClarks is rounding out its Fall/Winter 2026 offering with the Walla Eden GTX, a sports-casual silhouette engineered to hold up against the season's wetter days. Filed under the brand's ORIGINALs Classic Series, the shoe leans on tested materials rather than a flashy redesign, prioritizing function without straying far from the label's familiar silhouette.At the core of the Walla Eden GTX is its genuine leather construction, a material choice that grounds the shoe in durability while keeping the upper supple enough for daily wear. Layered onto that leather base is GTX waterproof technology, giving the silhouette a barrier against rain and standing water that most casual sneakers can't claim.That comb",
   "image": "https://image-cdn.hypb.st/https%3A%2F%2Fhypebeast.com%2Fimage%2F2026%2F09%2F10%2FftClarks-Originals-Walla-Eden-GTX-Black-CLM27893R-Official-Images-Taiwan-Release-Info.jpg?w=800&cbr=1&q=90&fit=max",
   "link": "https://hypebeast.com/2026/9/clarks-originals-walla-eden-gtx-black-clm27893r-official-images-taiwan-release-info",
   "lang": "en",
   "relatedBrands": [
    "CLARKS"
   ]
  },
  {
   "id": 4,
   "title": "Best Footwear Trends at Tokyo Fashion Week SS27",
   "source": "Hypebeast",
   "date": "2026-09-10",
   "content": "Summary Tokyo Fashion Week SS27 street style highlighted an expansive mix of technical runners luxury silhouettes and avant-garde footwearKey callouts featured high-profile collaborations alongside tactile releases from Doublet MIKIOSAKABE and Comme des Garçons x SalomonThe footwear lineup emphasized hybrid designs ranging from indoor soccer trainers to chunky platform soles and spiked canvas uppers Footwear at Tokyo Fashion Week Spring/Summer 2027 delivered a dynamic cross-section of technical performance, archival indoor sport references, and avant-garde experimentation. On the streets of the Japanese capital, showgoers anchored their fits with an eclectic mix of functional runners, high-concept platform soles, and sleek low-profile models.Running and trail silhouettes maintained a heavy presence on the pavement. Technical highlights included the hybrid Nike Air Max Plus Tiempo in \"Wol",
   "image": "https://image-cdn.hypb.st/https%3A%2F%2Fhypebeast.com%2Fimage%2F2026%2F09%2F09%2Fbest-footwear-trends-tokyo-fashion-week-ss27-000.jpg?w=800&cbr=1&q=90&fit=max",
   "link": "https://hypebeast.com/2026/9/best-footwear-trends-tokyo-fashion-week-ss27",
   "lang": "en",
   "relatedBrands": [
    "ADIDAS",
    "ASICS",
    "BALENCIAGA",
    "HOKA",
    "MIZUNO",
    "NEW BALANCE",
    "NIKE",
    "PUMA",
    "SALOMON"
   ]
  },
  {
   "id": 5,
   "title": "Simone Rocha Has Made adidas’ Ballet Dreams a Reality",
   "source": "Highsnobiety",
   "date": "2026-09-10",
   "content": "Simone Rocha and adidas reunite for Fall/Winter 2026 with a ballet-inspired take on the iconic Taekwondo silhouette.",
   "image": "",
   "link": "https://www.highsnobiety.com/p/adidas-simone-rocha-taekwondo-ballerina/",
   "lang": "en",
   "relatedBrands": [
    "ADIDAS"
   ]
  },
  {
   "id": 6,
   "title": "The North Face x Engineered Garments 推出 VECTIV Forward",
   "source": "Hypebeast 中文",
   "date": "2026-09-09",
   "content": "摘要The North Face 與 Engineered Garments 推出 VECTIV Forward，這雙兼具日常風格與跑鞋機能的鞋款採用模組化設計，可在繫帶與套穿兩種穿法之間轉換。這雙海軍藍／黑色球鞋將於 2026 年 9 月 11 至 12 日推出，結合實用主義設計與 3D Pebax 板、DREAM 泡棉等性能科技。The North Face 與 Engineered Garments 首度聯乘，帶來用途多元的 VECTIV Forward 鞋型。這雙限量鞋款的核心在於其模組化設計，靈感來自設計師 Daiki Suzuki 的實用主義取向，以及這個戶外裝備品牌的性能專長。原為跑步而設的球鞋輪廓持續受到時尚界青睞，要同時兼顧機能與造型，正推動各種創新方案。這款融合日常風格與跑鞋機能的鞋款採用可變換的雙向設計：認真跑步時可使用傳統鞋帶；日常穿著時則可換上配套鞋舌罩，作套穿鞋款使用。鞋底配備 VECTIV 3D Pebax 及碳纖維板、DREAM 泡棉中底、搖桿結構，以及外底的高抓地力 SurfaceCTRL™，帶來推進力與穩定性。這雙鞋既適合高強度跑步，也適合悠閒散步，並以單色調「Easy Navy/TNF Black」配色登場，平衡性能與簡約風格。The North Face x Engineered Garments VECTIV Forward 將於 2026 年 9 月 11 日星期五率先在 THE NORTH FACE FOOTWEAR Shinsaibashi 及 ENGINEERED GARMENTS TOKYO 預售，並於 9 月 12 日星期六起在網上及全國發售。 Click here to view full gallery at Hypebeast",
   "image": "https://image-cdn.hypb.st/https%3A%2F%2Fhk.hypebeast.com%2Ffiles%2F2026%2F09%2Fthe-north-face-engineered-garments-vectiv-forward-sneaker-release-date-info-0.jpg?w=800&cbr=1&q=90&fit=max",
   "link": "https://hypebeast.com/zh/2026/9/the-north-face-engineered-garments-vectiv-forward-sneaker-release-date-info",
   "lang": "zh",
   "relatedBrands": []
  },
  {
   "id": 7,
   "title": "Converse Japan All Star Yunomi Hi 以茶杯魚字旁圖案鋪滿高筒鞋身",
   "source": "Hypebeast 中文",
   "date": "2026-09-09",
   "content": "名稱： Converse Japan All Star Yunomi Hi配色：白色／海軍藍貨號：31319350210建議零售價：11,000 日圓（約 70 美元）發售日期：9 月 25 日發售地點：Converse JapanConverse Japan 將日常餐桌器皿化作覆蓋整雙鞋的圖案，於這雙帆布高筒鞋印上日式茶杯「湯吞」的圖案。鞋款採用更新版 All Star 規格，並以鞋面作畫布，呈現細節密集、充滿日式風格的印花。圖案正是此鞋的主角。Converse Japan 從湯吞汲取靈感；這種茶杯在日本紀念品店隨處可見，其圖像如今被移植到鞋上。這類茶杯常飾以魚字旁漢字，鞋面印花亦延續這項傳統，散布著各個相關漢字。設計還融入兩項呼應品牌的元素。其一是以漢字寫成的「all star」，以日文漢字而非慣常的拉丁字母拼寫鞋款名稱。其二是在文字之間加入一組手繪星星，以較隨性的素描筆觸襯托印刷字樣，同時呼應 All Star 的核心標誌。圖案之下，鞋款結構依然忠於原有輪廓。更新版 All Star 規格配備帆布鞋面及橡膠外底，延續這個鞋型數十年來標誌性的高筒剪裁。 Click here to view full gallery at Hypebeast",
   "image": "https://image-cdn.hypb.st/https%3A%2F%2Fhk.hypebeast.com%2Ffiles%2F2026%2F09%2FftConverse-Japan-All-Star-Yunomi-Hi-Teacup-Inspired-fish-kanji-31319350210-Release-Info.jpg?w=800&cbr=1&q=90&fit=max",
   "link": "https://hypebeast.com/zh/2026/9/converse-japan-all-star-yunomi-hi-teacup-inspired-fish-kanji-31319350210-release-info",
   "lang": "zh",
   "relatedBrands": [
    "CONVERSE"
   ]
  },
  {
   "id": 8,
   "title": "PUMA x _J.L-A.L CELL GEO 1 CAGE JL-AL 最新官方照片釋出",
   "source": "Hypebeast 中文",
   "date": "2026-09-09",
   "content": "名稱： PUMA x _J.L-A.L CELL GEO 1 CAGE JL-AL配色： 待定貨號： 待定建議零售價： 33,000 日圓（約 215 美元）發售日期： 9 月 12 日發售渠道： PUMAPUMA 與倫敦服飾品牌 _J.L-A.L 攜手推出最新聯乘鞋款 CELL GEO 1 CAGE J.L-A.L。品牌由設計師 Jean-Luc Ambridge Lavelle 主理，新作由此前售罄的 CELL GEO 演變而來，鞋身採用引人注目的幾何設計，靈感取自建築師 Buckminster Fuller 的測地線圓頂結構。這雙主打性能的球鞋採用無縫、無鞋帶網布鞋面，外覆 3D TPU 籠狀結構，兼具結構美感與流暢的未來感造型。CELL GEO 1 CAGE J.L-A.L 備有深啡及白色兩款純色配色，以極簡風格融入機能服飾元素。鞋面覆以三角形籠狀飾層，為透氣網布基底增添視覺層次；後跟部件則採功能性分區設計，提升整體結構穩定性。 Click here to view full gallery at Hypebeast",
   "image": "https://image-cdn.hypb.st/https%3A%2F%2Fhk.hypebeast.com%2Ffiles%2F2026%2F09%2Fftpuma-j-la-l-cell-geo-1-cage-jl-al-official-images-release-info.jpg?w=800&cbr=1&q=90&fit=max",
   "link": "https://hypebeast.com/zh/2026/9/puma-j-la-l-cell-geo-1-cage-jl-al-official-images-release-info",
   "lang": "zh",
   "relatedBrands": [
    "PUMA"
   ]
  },
  {
   "id": 9,
   "title": "ANTA KAI 3「Alchemist」將 Kyrie Irving 的哲學融入全新配色",
   "source": "Hypebeast 中文",
   "date": "2026-09-09",
   "content": "鞋名：ANTA KAI 3「Alchemist」配色：「Alchemist」產品編號：待定建議零售價：135 美元發售日期：9 月 12 日發售地點：ANTAKyrie Irving 與 ANTA 將推出備受期待的 KAI 3「Alchemist」配色，進一步拓展雙方成功的籃球合作關係。球鞋搭載 ANTA 先進的緩震與抓地系統，兼顧精準的技術表現與文化象徵，呼應 Irving 將挑戰化為力量、鼓舞隊友與社群的理念。「Alchemist」配色以深邃的森林綠鋪陳鞋面，象徵大地、智慧與隱藏的力量；富質感的鞋面基底配上亮眼的青綠色支撐片，並印有若隱若現的格紋圖案，鋸齒狀側面穩定片則綴以金屬金色。鞋身加入部落風格細節，進一步展現文化元素，與中底及外底的螢光黃色和啞金色飾面形成對比。最上方鞋帶還垂墜一條金色「生命之樹」徽章鏈，為設計畫上句點。 Click here to view full gallery at Hypebeast",
   "image": "https://image-cdn.hypb.st/https%3A%2F%2Fhk.hypebeast.com%2Ffiles%2F2026%2F09%2Fkyrie-irving-anta-kai-3-alchemist-release-info-0.jpg?w=800&cbr=1&q=90&fit=max",
   "link": "https://hypebeast.com/zh/2026/9/kyrie-irving-anta-kai-3-alchemist-release-info",
   "lang": "zh",
   "relatedBrands": []
  },
  {
   "id": 10,
   "title": "UNDERCOVER 與 George Cox 以 Cindy Sherman 攝影作品重塑 4 Eyelet Derby",
   "source": "Hypebeast 中文",
   "date": "2026-09-09",
   "content": "名稱： UNDERCOVER x Cindy Sherman x George Cox 4 Eyelet Derby配色：黑色、白色產品編號：不適用建議零售價：450 美元發售日期：現已發售發售地點：George CoxGeorge Cox 與 UNDERCOVER 再度攜手推出 4 Eyelet Derby，延續 Jun Takahashi 旗下品牌與 George Cox 位於 Northamptonshire 的工坊之間的合作。來到 2026 秋冬季度，雙方將這款鞋交予美國藝術家 Cindy Sherman 演繹，讓她探究身分認同的攝影作品成為鞋身表面。鞋款結構忠於 George Cox 一貫的製作方法。兩種配色均採用 1353 鞋楦，這是源自 Northamptonshire 的傳統圓頭鞋楦；品牌藉此塑造出比其經典鞋型所呈現的更硬朗輪廓。每雙鞋均配備輕量 EVA 鞋底，並以鋼製鞋眼扣固定四孔鞋帶，亦正是 4 Eyelet Derby 名稱的由來。鞋內採用天然小牛皮作內裡，並保留 George Cox 視為品牌標誌筆觸一部分的工業壓印內部細節。George Cox 與 UNDERCOVER 沒有為皮革染色或壓紋，而是直接印上照片，讓 Sherman 的影像包覆整個鞋身，形成連貫的畫面，焦點則落在鞋頭位置。Sherman 以精心佈置的自拍肖像建立聲譽，在鏡頭前化身不斷轉換的角色，藉攝影探問身分如何被建構與演繹。這種對自我形象的關注，亦恰好呼應 UNDERCOVER 一直以來的顛覆精神。兩種配色分別取材自她不同的作品。白色款印有她於 1983 年創作的 《Untitled #122》；黑色款則取自她較早期的電影劇照系列，呈現 1979 年的 《Untitled Film Still #16》及 1980 年的 《Untitled Film Still #53》。兩款鞋的影像素材橫跨 1979 至 1983 年，令這雙 Derby 鞋化作美國當代攝影最具影響力作品群之一的可穿戴片段。 Click here to view full gallery at Hypebeas",
   "image": "https://image-cdn.hypb.st/https%3A%2F%2Fhk.hypebeast.com%2Ffiles%2F2026%2F09%2FUNDERCOVER-Cindy-Sherman-George-Cox-4-Eyelet-Derby-black-white-Release-Info-1.jpg?w=800&cbr=1&q=90&fit=max",
   "link": "https://hypebeast.com/zh/2026/9/undercover-cindy-sherman-george-cox-4-eyelet-derby-black-white-release-info",
   "lang": "zh",
   "relatedBrands": []
  },
  {
   "id": 11,
   "title": "JJJJound 與 Diemme 再推 Movida「Brown」麖皮配色，採用意大利皮革及 Vibram 鞋底",
   "source": "Hypebeast 中文",
   "date": "2026-09-09",
   "content": "名稱： JJJJound x Diemme Movida配色： 啡色SKU： 不適用建議零售價： 待定發售日期： 9 月 10 日發售地點： JJJJound、DiemmeDiemme 與 JJJJound 為 Movida 換上啡色麖皮配色，延續雙方持續回歸意大利品牌實用鞋履輪廓的合作。這雙最新鞋款於意大利手工製作，以材質和結構為重點，選用優質意大利麖皮鞋面，配以全皮革內裡。鞋款以輕量 Vibram 鞋底作基礎，著重日常穿著所需的靈活度與抓地力，而非純粹應付高性能用途。啡色麖皮鞋面配上全皮革內裡，既呼應 Diemme 的機能製鞋背景，亦令整體輪廓保持簡潔，符合 JJJJound 一貫的極簡美學。細節正是這次合作的個性所在。黑色塗層金屬鞋眼配以黑色聚酯纖維鞋帶，另穿上一條紅色副鞋帶，低調帶出對比效果。編織尼龍後拉環和織帶提拉環兼具實用功能，方便穿著，同時呼應 Diemme 從戶外鞋款汲取的設計原型。鞋頭與鞋跟的品牌標記同樣保持低調：鞋舌壓印 Diemme 標誌，鞋跟拉片則印有 JJJJound 的襯線字標，讓兩個品牌各自表明身分，卻不破壞極簡的整體處理。Diemme 自 1992 年起在意大利 Veneto 地區的基地製作鞋履，從登山及高性能裝備汲取靈感，打造兼具精緻感與實用取向的設計；這份傳承貫穿今次鞋款的每一個元素。 Click here to view full gallery at Hypebeast",
   "image": "https://image-cdn.hypb.st/https%3A%2F%2Fhk.hypebeast.com%2Ffiles%2F2026%2F09%2Fft-JJJJound-Diemme-Movida-Brown-Release-Info.jpg?w=800&cbr=1&q=90&fit=max",
   "link": "https://hypebeast.com/zh/2026/9/jjjjound-diemme-movida-brown-release-info",
   "lang": "zh",
   "relatedBrands": []
  },
  {
   "id": 12,
   "title": "N.HOOLYWOOD COMPILE x KEEN 將 UNEEK 360 簡化為繩索、鞋底與無膠結構",
   "source": "Hypebeast 中文",
   "date": "2026-09-09",
   "content": "名稱：N.HOOLYWOOD COMPILE x KEEN UNEEK 360配色：Steel Gray貨號：1032697建議零售價：25,300 日圓（約 165 美元）發售日期：9 月 12 日發售地點：N.HOOLYWOOD、KEEN JapanN.HOOLYWOOD COMPILE 與 KEEN 首度聯乘，選用 KEEN 開放式 UNEEK 系列的最新鞋型 UNEEK 360。偏向正裝風格的 N.HOOLYWOOD 支線以自身手法重構這雙鞋，在突顯鞋款精簡結構之餘，注入更為講究的質感。設計起點源自 UNEEK「僅以繩索與鞋底構成一雙鞋」的概念。KEEN 為此版本採用完全不用黏合劑的結構，並以減少廢料為原則重塑鞋型。鞋身以再生塑膠製成的彈力繩，配合鞋帶扣快速固定雙足；鞋面亦預留空間讓腳趾自然張開，以適應不同腳型。其餘規格則著重舒適度與耐用性。按足形塑造的足弓支撐加強中足承托，注塑泡棉中底令腳感保持輕盈，內置足弓支撐的泡棉鞋墊則為長時間穿著提供緩震。高抓地力泡棉外底兼顧防滑與耐磨，全鞋重量為 322 克。物料選擇亦貫徹可持續理念：混入再生 PET 的塑膠減少原生物料用量，而天然來源的 Eco Anti-odor 抗臭處理則有助抑制異味。N.HOOLYWOOD COMPILE 的印記則見於取捨之間。這個支線一向將正裝與禮服的設計語言轉化為當代輕鬆穿搭，而此鞋正以克制手法呈現：由鞋面延伸至鞋底的單一灰色調，僅在鞋跟低調印上 N.HOOLYWOOD 標誌。官方命名為 Steel Gray 的配色，讓 UNEEK 360 的極簡結構成為焦點，也令它不偏向城市街頭或戶外任何一方，而是適合穿梭兩者之間。 Click here to view full gallery at Hypebeast",
   "image": "https://image-cdn.hypb.st/https%3A%2F%2Fhk.hypebeast.com%2Ffiles%2F2026%2F09%2FN-HOOLYWOOD-Compile-KEEN-UNEEK-360-Steel-Gray-1032697-Release-Info-0.jpg?w=800&cbr=1&q=90&fit=max",
   "link": "https://hypebeast.com/zh/2026/9/n-hoolywood-compile-keen-uneek-360-steel-gray-1032697-release-info",
   "lang": "zh",
   "relatedBrands": []
  },
  {
   "id": 13,
   "title": "The North Face x Engineered Garments Introduce the VECTIV Forward",
   "source": "Hypebeast",
   "date": "2026-09-09",
   "content": "SummaryThe North Face and Engineered Garments debut the VECTIV Forward, a modular lifestyle-runner convertible between laced and slip-on styles.Launching September 11-12, 2026, the navy/black sneaker blends utilitarian design with performance tech like 3D Pebax plates and DREAM foam.The North Face and Engineered Garments have partnered up for their first-ever collaboration, dropping the versatile VECTIV Forward silhouette. Central to the limited-edition pair is a modular design inspired by designer Daiki Suzuki's utilitarian approach and the outdoor gear label’s performance expertise.As sneaker silhouettes originally made for running continue to be embraced by fashion, the need to equally address both function and form is driving innovative solutions. This lifestyle-runner hybrid boasts a transformable two-way design, allowing the wearer to choose between traditional laces for serious ru",
   "image": "https://image-cdn.hypb.st/https%3A%2F%2Fhypebeast.com%2Fimage%2F2026%2F09%2F09%2Fthe-north-face-engineered-garments-vectiv-forward-sneaker-release-date-info-0.jpg?w=800&cbr=1&q=90&fit=max",
   "link": "https://hypebeast.com/2026/9/the-north-face-engineered-garments-vectiv-forward-sneaker-release-date-info",
   "lang": "en",
   "relatedBrands": []
  },
  {
   "id": 14,
   "title": "Converse Japan's All Star Yunomi Hi Pours a Teacup's Fish Kanji Print Onto a High-Top",
   "source": "Hypebeast",
   "date": "2026-09-09",
   "content": "Name: Converse Japan All Star Yunomi HiColorway: White/NavySKU: 31319350210MSRP: ¥11,000 JPY (approx. $70 USD)Release Date: September 25Where to Buy: Converse JapanConverse Japan's All Star Yunomi Hi turns a piece of everyday tableware into a full-coverage sneaker graphic, printing the motif of the yunomi teacup across a canvas high-top. The release lands on a renewed version of the All Star spec and treats the upper as a canvas for a densely detailed, distinctly Japanese print.The graphic is the whole story here. Converse Japan draws on the yunomi, the style of teacup familiar to anyone who has browsed a Japanese souvenir shop, and translates its imagery onto the shoe. Teacups of this kind are frequently decorated with kanji built on the fish radical, and the print leans into that tradition, scattering those characters across the upper.Woven into the design are two additional touches th",
   "image": "https://image-cdn.hypb.st/https%3A%2F%2Fhypebeast.com%2Fimage%2F2026%2F09%2F09%2FftConverse-Japan-All-Star-Yunomi-Hi-Teacup-Inspired-fish-kanji-31319350210-Release-Info.jpg?w=800&cbr=1&q=90&fit=max",
   "link": "https://hypebeast.com/2026/9/converse-japan-all-star-yunomi-hi-teacup-inspired-fish-kanji-31319350210-release-info",
   "lang": "en",
   "relatedBrands": [
    "CONVERSE"
   ]
  },
  {
   "id": 15,
   "title": "Official Look at the PUMA CELL GEO 1 CAGE JL-AL",
   "source": "Hypebeast",
   "date": "2026-09-09",
   "content": "Name: PUMA x _J.L‑A.L CELL GEO 1 CAGE JL-ALColorway: TBCSKU: TBCMSRP: ¥33,000 JPY (approx. $215 USD)Release Date: September 12Where to Buy: PUMAPUMA and London-based apparel brand _J.L-A.L, helmed by designer Jean-Luc Ambridge Lavelle, have unveiled their latest collaborative footwear model, the CELL GEO 1 CAGE J.L-A.L. Evolving from their previous sold-out CELL GEO, this new silhouette introduces a striking geometric design inspired by the geodesic dome structures of architect Buckminster Fuller.The performance-driven sneaker features a seamless, laceless mesh upper enveloped by a 3D TPU cage system, delivering both structural beauty and a fluid, futuristic form. Offered in stark, monochromatic dark brown and white colorways, the CELL GEO 1 CAGE J.L-A.L embraces a minimalist aesthetic with a techwear edge. The upper is draped in a triangular cage overlay that adds visual depth to the br",
   "image": "https://image-cdn.hypb.st/https%3A%2F%2Fhypebeast.com%2Fimage%2F2026%2F09%2F09%2Fftpuma-j-la-l-cell-geo-1-cage-jl-al-official-images-release-info.jpg?w=800&cbr=1&q=90&fit=max",
   "link": "https://hypebeast.com/2026/9/puma-j-la-l-cell-geo-1-cage-jl-al-official-images-release-info",
   "lang": "en",
   "relatedBrands": [
    "PUMA"
   ]
  },
  {
   "id": 16,
   "title": "ANTA’s KAI 3 “Alchemist” Turns Kyrie Irving's Philosophy Into a new Colorway",
   "source": "Hypebeast",
   "date": "2026-09-09",
   "content": "Name: ANTA KAI 3 “Alchemist”Colorway: “Alchemist”SKU: TBCMSRP: $135 USDRelease Date: September 12Where to Buy: ANTAKyrie Irving and ANTA are set to expand their successful basketball partnership with the launch of the KAI 3 in a highly anticipated “Alchemist” colorway.Built with ANTA’s advanced cushioning and traction systems, the sneaker balances technical precision with cultural symbolism, reflecting Irving’s philosophy of turning challenges into strength and uplifting his team and community. The \"Alchemist\" colorway is draped in a deep forest green across its upper, serving as a visual representation of earth, wisdom and hidden power. The rich, textured base is accented by vibrant teal support panels featuring a faint plaid print, while metallic gold shines on the zig-zagging side panel stabilizers.Tribal-inspired detailing brings an added layer of cultural influence to the silhouette",
   "image": "https://image-cdn.hypb.st/https%3A%2F%2Fhypebeast.com%2Fimage%2F2026%2F09%2F09%2Fkyrie-irving-anta-kai-3-alchemist-release-info-0.jpg?w=800&cbr=1&q=90&fit=max",
   "link": "https://hypebeast.com/2026/9/kyrie-irving-anta-kai-3-alchemist-release-info",
   "lang": "en",
   "relatedBrands": []
  },
  {
   "id": 17,
   "title": "UNDERCOVER and George Cox Reinterpret the 4 Eyelet Derby Through Cindy Sherman's Photography",
   "source": "Hypebeast",
   "date": "2026-09-09",
   "content": "Name: UNDERCOVER x Cindy Sherman x George Cox 4 Eyelet DerbyColorway: Black, WhiteSKU: N/AMSRP: $450 USDRelease Date: Available nowWhere to Buy: George CoxGeorge Cox and UNDERCOVER have again joined forces on the 4 Eyelet Derby, extending a partnership that runs through Jun Takahashi's label and George Cox's Northamptonshire workshop. For Fall/Winter 2026, the two houses hand the silhouette over to American artist Cindy Sherman, whose photographic studies of identity become the surface of the shoe itself.The construction stays true to George Cox's house methods. Both colorways are built on the 1353 last, a traditional Northamptonshire round-toe form that the brand pushes into something tougher than its heritage silhouettes suggest. A lightweight EVA sole underpins each pair, while steel eyelets handle the four-eyelet lacing that gives the derby its name. Inside, the shoes are finished wi",
   "image": "https://image-cdn.hypb.st/https%3A%2F%2Fhypebeast.com%2Fimage%2F2026%2F09%2F09%2FUNDERCOVER-Cindy-Sherman-George-Cox-4-Eyelet-Derby-black-white-Release-Info-1.jpg?w=800&cbr=1&q=90&fit=max",
   "link": "https://hypebeast.com/2026/9/undercover-cindy-sherman-george-cox-4-eyelet-derby-black-white-release-info",
   "lang": "en",
   "relatedBrands": [
    "UGG"
   ]
  },
  {
   "id": 18,
   "title": "JJJJound and Diemme Return the Movida in a \"Brown\" Suede Build With Italian Leather and Vibram",
   "source": "Hypebeast",
   "date": "2026-09-09",
   "content": "Name: JJJJound x Diemme MovidaColorway: BrownSKU: N/AMSRP: TBCRelease Date: September 10Where to Buy: JJJJound, DiemmeDiemme and JJJJound have reworked the Movida in a brown suede colorway, extending a collaboration that keeps returning to the Italian label's utilitarian silhouettes. Handcrafted in Italy, the latest pair leads with material and construction, building the shoe from premium Italian suede over a full leather lining.The foundation is a lightweight Vibram sole, chosen to deliver flexibility and grip for daily wear rather than pure performance duty. Above it, the brown suede upper sits on a full leather lining, a combination that leans on Diemme's technical shoemaking background while keeping the profile clean enough for JJJJound's pared-back sensibility.The detailing is where the collaboration earns its character. Black-coated metal eyelets secure black polyester laces, with ",
   "image": "https://image-cdn.hypb.st/https%3A%2F%2Fhypebeast.com%2Fimage%2F2026%2F09%2F09%2Fft-JJJJound-Diemme-Movida-Brown-Release-Info.jpg?w=800&cbr=1&q=90&fit=max",
   "link": "https://hypebeast.com/2026/9/jjjjound-diemme-movida-brown-release-info",
   "lang": "en",
   "relatedBrands": []
  },
  {
   "id": 19,
   "title": "N.HOOLYWOOD COMPILE x KEEN Pare the UNEEK 360 Down to Cords, a Sole and a Glue-Free Build",
   "source": "Hypebeast",
   "date": "2026-09-09",
   "content": "Name: N.HOOLYWOOD COMPILE x KEEN UNEEK 360Colorway: Steel GraySKU: 1032697MSRP: ¥25,300 JPY (approx. $165 USD)Release Date: September 12Where to Buy: N.HOOLYWOOD, KEEN JapanN.HOOLYWOOD COMPILE and KEEN have built their first collaboration on the UNEEK 360, the newest model in KEEN's open-air UNEEK series. The dress-leaning N.HOOLYWOOD line reconstructs the sneaker on its own terms, keeping the model's stripped-back engineering front and center while pulling it toward a more refined finish.The starting point is the UNEEK concept of a shoe made from little more than cords and a sole. For this version, KEEN adopts a build that uses no adhesive, reconstructing the silhouette around that minimal-waste logic. Recycled-plastic bungee cord and a lace toggle lock the foot in place quickly, while the upper is shaped to leave room for the toes to splay, aiming for a fit that works across a wide ran",
   "image": "https://image-cdn.hypb.st/https%3A%2F%2Fhypebeast.com%2Fimage%2F2026%2F09%2F09%2FN-HOOLYWOOD-Compile-KEEN-UNEEK-360-Steel-Gray-1032697-Release-Info-0.jpg?w=800&cbr=1&q=90&fit=max",
   "link": "https://hypebeast.com/2026/9/n-hoolywood-compile-keen-uneek-360-steel-gray-1032697-release-info",
   "lang": "en",
   "relatedBrands": []
  },
  {
   "id": 20,
   "title": "Nike Ja 4 “Jaws” September 2026 Release Date & Info",
   "source": "Nice Kicks",
   "date": "2026-09-09",
   "content": "The Nike Ja 4 “Jaws” is set to release on September 25, 2026, via Nike.com and select retailers for $130. Ja Morant debuted his… The post Nike Ja 4 “Jaws” September 2026 Release Date & Info appeared first on Nice Kicks .",
   "image": "https://www.nicekicks.com/files/2026/09/IMG_3152-e1788996693405.jpg",
   "link": "https://www.nicekicks.com/nike-ja-4-jaws-im4135-401/",
   "lang": "en",
   "relatedBrands": [
    "NIKE"
   ]
  },
  {
   "id": 21,
   "title": "Nike Air Force 1 Low Cracked Leather “Menta”",
   "source": "Nice Kicks",
   "date": "2026-09-09",
   "content": "The Nike Air Force 1 Low Cracked Leather “Menta” is expected to release in Fall of 2026, via select retailers… The post Nike Air Force 1 Low Cracked Leather “Menta” appeared first on Nice Kicks .",
   "image": "https://www.nicekicks.com/files/2026/09/imgi_1_snkrs-verified-september-2026-1-2-e1788994582707.jpeg",
   "link": "https://www.nicekicks.com/nike-air-force-1-low-cracked-leather-menta-ja0248-300/",
   "lang": "en",
   "relatedBrands": [
    "NIKE"
   ]
  },
  {
   "id": 22,
   "title": "Nike Air Force 1 Low Cracked Leather “Black”",
   "source": "Nice Kicks",
   "date": "2026-09-09",
   "content": "The Nike Air Force 1 Low Cracked Leather “Black” is set to release on September 22, 2026, via select retailers… The post Nike Air Force 1 Low Cracked Leather “Black” appeared first on Nice Kicks .",
   "image": "https://www.nicekicks.com/files/2026/09/imgi_1_snkrs-verified-september-2026-5-e1788994458129.jpeg",
   "link": "https://www.nicekicks.com/nike-air-force-1-low-cracked-leather-black-ja0248-001/",
   "lang": "en",
   "relatedBrands": [
    "NIKE"
   ]
  },
  {
   "id": 23,
   "title": "Nike G.T. Future “Varsity Red”",
   "source": "Nice Kicks",
   "date": "2026-09-09",
   "content": "The Nike G.T. Future “Varsity Red” is releasing on September 8, 2026, via select retailers. A global launch will take place on… The post Nike G.T. Future “Varsity Red” appeared first on Nice Kicks .",
   "image": "https://www.nicekicks.com/files/2026/09/fz5590-603-5-e1788874012997.jpg",
   "link": "https://www.nicekicks.com/nike-g-t-future-varsity-red-fz5590-603/",
   "lang": "en",
   "relatedBrands": [
    "NIKE"
   ]
  },
  {
   "id": 24,
   "title": "Larry June Brings Good Job Energy to the adidas Adistar Control 5",
   "source": "Nice Kicks",
   "date": "2026-09-09",
   "content": "After his first adidas Adistar Control 5 was reserved for Friends & Family, Larry June is bringing the retro runner… The post Larry June Brings Good Job Energy to the adidas Adistar Control 5 appeared first on Nice Kicks .",
   "image": "https://www.nicekicks.com/files/2026/09/imgi_1_37134183_69657002_1000-e1788465100913.jpg",
   "link": "https://www.nicekicks.com/larry-june-adidas-adistar-control-5-watermelon-smoothie-kz7294/",
   "lang": "en",
   "relatedBrands": [
    "ADIDAS"
   ]
  },
  {
   "id": 25,
   "title": "Jordan Tatum 5 “Sunrise”",
   "source": "Nice Kicks",
   "date": "2026-09-09",
   "content": "The Jordan Tatum 5 is built around Jayson Tatum’s controlled style of play, combining a lightweight feel with a utility… The post Jordan Tatum 5 “Sunrise” appeared first on Nice Kicks .",
   "image": "https://www.nicekicks.com/files/2026/09/jordan-brand-tatum-5-sunrise-kids-1-scaled-e1788995342490.jpg",
   "link": "https://www.nicekicks.com/jordan-tatum-5-sunrise-io1746-401/",
   "lang": "en",
   "relatedBrands": [
    "JORDAN"
   ]
  },
  {
   "id": 26,
   "title": "Jayson Tatum’s Jordan Tatum 5 Marks a New Chapter After His Achilles Injury",
   "source": "Nice Kicks",
   "date": "2026-09-09",
   "content": "Jordan Brand is introducing the Jordan Tatum 5, the fifth signature sneaker for Jayson Tatum and perhaps the most personal… The post Jayson Tatum’s Jordan Tatum 5 Marks a New Chapter After His Achilles Injury appeared first on Nice Kicks .",
   "image": "https://www.nicekicks.com/files/2026/09/Jordan_Tatum_5_lead.jpg",
   "link": "https://www.nicekicks.com/jayson_tatum_5_jordan_sneaker/",
   "lang": "en",
   "relatedBrands": [
    "JORDAN"
   ]
  },
  {
   "id": 27,
   "title": "Air Jordan 7 “Tennis Day” September 2026 Release Date & Info",
   "source": "Nice Kicks",
   "date": "2026-09-09",
   "content": "Readers can expect the Air Jordan 7 “Tennis Day” to release on September 9, 2026, via Nike.com and select retailers for $215. Check out… The post Air Jordan 7 “Tennis Day” September 2026 Release Date & Info appeared first on Nice Kicks .",
   "image": "https://www.nicekicks.com/files/2026/08/iv6508-030-5-1-e1787670238928.jpg",
   "link": "https://www.nicekicks.com/air-jordan-7-tennis-day-iv6508-030/",
   "lang": "en",
   "relatedBrands": [
    "JORDAN",
    "NIKE"
   ]
  },
  {
   "id": 28,
   "title": "Nike Will Never Be the Same",
   "source": "Highsnobiety",
   "date": "2026-09-09",
   "content": "Nike's share price is at record lows as it gets removed from the S&P 100, but don't be too quick to count out the Swoosh. An all-new Nike is (surely) en route.",
   "image": "",
   "link": "https://www.highsnobiety.com/p/nike-stock-price/",
   "lang": "en",
   "relatedBrands": [
    "NIKE"
   ]
  },
  {
   "id": 29,
   "title": "adidas' Military Vet Is on a Midnight Mission",
   "source": "Highsnobiety",
   "date": "2026-09-09",
   "content": "The adidas Originals BW Army Shadow Navy coats the essential in deep, atmospheric tones.",
   "image": "",
   "link": "https://www.highsnobiety.com/p/adidas-bw-army-sahdow-navy-charcoal/",
   "lang": "en",
   "relatedBrands": [
    "ADIDAS"
   ]
  },
  {
   "id": 30,
   "title": "Pickle Juice & Lichen Camo: Nike ACG Put Us Through All Conditions",
   "source": "Highsnobiety",
   "date": "2026-09-09",
   "content": "Nike ACG put us through all conditions as we were set to watch the biggest race in trial running, UTMB.",
   "image": "",
   "link": "https://www.highsnobiety.com/p/nike-acg-put-us-through-all-conditions/",
   "lang": "en",
   "relatedBrands": [
    "NIKE"
   ]
  },
  {
   "id": 31,
   "title": "From Saucony to adidas, the Seven Best Sneakers to Cop This Week",
   "source": "Highsnobiety",
   "date": "2026-09-09",
   "content": "This weeks packed full of funky collaborations and crazy colorways, before we all go back to muter winter sneakers.",
   "image": "",
   "link": "https://www.highsnobiety.com/p/sneaker-releases-2026-september-week-2/",
   "lang": "en",
   "relatedBrands": [
    "ADIDAS",
    "SAUCONY"
   ]
  },
  {
   "id": 32,
   "title": "Celine 為 Reebok Freestyle Lo 注入巴黎風格新貌",
   "source": "Hypebeast 中文",
   "date": "2026-09-08",
   "content": "摘要Celine/Reebok Freestyle Lo 將於 9 月 10 日推出，以柔滑羊皮和醒目的雙方品牌標誌，重新演繹 1982 年的經典鞋款。Michael Rider 設計的鞋款將透過 Celine 官方網站及指定門市推出多款配色，紐約和東京更會有門市獨家色調。Michael Rider 於 6 月舉行的 Celine 2027 春夏男裝首秀上預告這次聯乘後，這個巴黎品牌現正式揭曉 Celine/Reebok Freestyle Lo。這款復古鞋型以多款單色配色重新登場，同時突顯品牌對鞋面的講究處理。初代 Freestyle Lo 誕生於 1982 年，具備日常休閒運動鞋的經典外觀，鞋身外側飾有辨識度極高的 Reebok 覆片。Rider 今次重新演繹此鞋款時，捨棄了覆片，讓焦點更集中於柔滑的羊皮鞋面。更新後的鞋型將推出多款百搭配色，包括亮白、黑色、奶油色、米色、花生色、深啡色、牛血紅及螢光紅。鞋頭線條簡潔流暢，令這雙聯乘鞋款帶有 Celine 薄底 Jazz Shoes 的相近氣質，惟鞋底更偏向運動風格。不過，鞋款大方地呈現雙方品牌標誌：最顯眼的是，鞋舌上經典的 Reebok 字樣標誌改為 Celine 徽章；鞋跟上方的後跟位置則飾有 Reebok 和 Celine 圖案。為添設計師巧思，每雙鞋均附有限量版皮革飾片，兩面分別印有雙方品牌標誌。Celine/Reebok Freestyle Lo 將於 9 月 10 日在 celine.com 及指定 Celine 門市發售。門市獨家配色將於紐約 Celine Wooster Street 及東京 Celine Omotesando 推出。 Click here to view full gallery at Hypebeast",
   "image": "https://image-cdn.hypb.st/https%3A%2F%2Fhk.hypebeast.com%2Ffiles%2F2026%2F09%2Fceline-reebok-freestyle-lo-release-date-info-0.jpg?w=800&cbr=1&q=90&fit=max",
   "link": "https://hypebeast.com/zh/2026/9/celine-reebok-freestyle-lo-release-date-info",
   "lang": "zh",
   "relatedBrands": [
    "CELINE",
    "REEBOK"
   ]
  },
  {
   "id": 33,
   "title": "Air Jordan 1 Low Element GTX 推出「Cream II」配色",
   "source": "Hypebeast 中文",
   "date": "2026-09-08",
   "content": "名稱：Air Jordan 1 Low Element GTX「Cream」配色：Cream II／淺 Orewood 啡／椰奶色－Ridgerock貨號：FV4227-202建議零售價：205 美元發售日期：2026 年全新亮相的 Air Jordan 1 Low Element GTX「Cream」，為這雙經典鞋型注入全天候機能，同時兼具日常穿搭感與技術性能。低筒鞋身設有 GORE-TEX 防水內襯，帶來耐用表現，亦能抵禦各種天氣。防水鞋面以柔和的「Cream II」與「淺 Orewood 啡」鋪陳，呈現易於融入日常造型的中性色調。醒目的黑色 Swoosh 與深啡色鞋領內襯營造刻意的對比；鞋舌標誌、拉環及 Swoosh 縫線上的細緻金色點綴，則為硬朗質感增添層次。斑點「椰奶色」中底搭配耐磨的「Ridgerock」外底，完整呼應實用機能美學，也進一步突顯其適合戶外穿著的功能。 Click here to view full gallery at Hypebeast",
   "image": "https://image-cdn.hypb.st/https%3A%2F%2Fhk.hypebeast.com%2Ffiles%2F2026%2F09%2Fair-jordan-1-low-element-gtx-cream-ii-light-orewood-brown-coconut-milk-ridgerock-fv4227-202-official-images-info-0.jpg?w=800&cbr=1&q=90&fit=max",
   "link": "https://hypebeast.com/zh/2026/9/air-jordan-1-low-element-gtx-cream-ii-light-orewood-brown-coconut-milk-ridgerock-fv4227-202-official-images-info",
   "lang": "zh",
   "relatedBrands": [
    "JORDAN"
   ]
  },
  {
   "id": 34,
   "title": "率先預覽 ROA x fragment design Andreas 靴款",
   "source": "Hypebeast 中文",
   "date": "2026-09-08",
   "content": "名稱：ROA x fragment design Andreas 靴款產品編號：待定發售日期：待定ROA 與 fragment design 聯乘打造的 Andreas 靴款，現已釋出率先預覽圖片。這雙鞋以藤原浩的極簡視角，重新詮釋 ROA 的機能戶外鞋型，呈現硬朗風格；皮革鞋面配以後跟穩定片，當中部分採用麖皮製成。繼 2017 年與 1017 ALYX 9SM 合作推出三方企劃後，雙方再度攜手；新曝光的鞋型似乎加強了保護性與耐用度，堅韌的黑色橡膠加固結構包覆鞋頭，在保留俐落低調外形之餘，亦突顯其戶外基因。單色鞋面加入金屬鞋帶鈎點綴，為傳統登山鞋帶系統注入一絲工業感。鞋底搭載重型 Vibram 外底，以其標誌性的黃色標誌辨認；品牌特別選用這款外底，看中其出色的耐用性與全地形抓地力。品牌標誌的處理恰到好處，ROA 的招牌三角標誌醒目地置於鞋舌及鞋頭，fragment design 的元素則一如既往地低調。後跟壓印 FRGMT 閃電圖案，低調表明藤原浩的影響力；鞋底一道搶眼的品牌標誌性藍色，亦與之相映成趣。這次備受期待的聯乘鞋款，官方發售日期及定價尚未公布。 Click here to view full gallery at Hypebeast",
   "image": "https://image-cdn.hypb.st/https%3A%2F%2Fhk.hypebeast.com%2Ffiles%2F2026%2F09%2Froa-fragment-design-andreas-boot-collaboration-first-look-info-0.jpg?w=800&cbr=1&q=90&fit=max",
   "link": "https://hypebeast.com/zh/2026/9/roa-fragment-design-andreas-boot-collaboration-first-look-info",
   "lang": "zh",
   "relatedBrands": []
  },
  {
   "id": 35,
   "title": "Celine Gave the Reebok Freestyle Lo a Parisian Remix",
   "source": "Hypebeast",
   "date": "2026-09-08",
   "content": "SummaryReleasing September 10, the Celine/Reebok Freestyle Lo reimagines the 1982 classic with smooth lambskin and prominent co-branding.Michael Rider’s design drops in multiple colorways via Celine’s website and select stores, featuring exclusive shades in NY and Tokyo.Following a teaser of the collaboration at Michael Rider's Celine SS27 Men's debut in June, the Parisian label has officially unveiled the Celine/Reebok Freestyle Lo. The retro silhouette is reintroduced in monochromatic yet wide-ranging colorways, emphasizing the maison's elevated treatment of the uppers.Born in 1982, the original Freestyle Lo has the classic look of an everyday lifestyle sneaker, adorned with the recognizable Reebok overlays on the lateral sides. For Rider's reimagination of the sneaker, the overlays are forgone to draw more attention to its smooth lambskin uppers. The updated silhouette will arrive in ",
   "image": "https://image-cdn.hypb.st/https%3A%2F%2Fhypebeast.com%2Fimage%2F2026%2F09%2F08%2Fceline-reebok-freestyle-lo-release-date-info-0.jpg?w=800&cbr=1&q=90&fit=max",
   "link": "https://hypebeast.com/2026/9/celine-reebok-freestyle-lo-release-date-info",
   "lang": "en",
   "relatedBrands": [
    "CELINE",
    "REEBOK"
   ]
  },
  {
   "id": 36,
   "title": "The Air Jordan 1 Low Element GTX Receives a “Cream II” Variant",
   "source": "Hypebeast",
   "date": "2026-09-08",
   "content": "Name: Air Jordan 1 Low Element GTX “Cream”Colorway: Cream II/Light Orewood Brown/Coconut Milk-RidgerockSKU: FV4227-202MSRP: $205 USDRelease Date: 2026The freshly surfaced Air Jordan 1 Low Element GTX “Cream” brings a weather-ready update to the classic silhouette, combining lifestyle appeal with technical performance. The sneaker features a GORE-TEX waterproof lining integrated into its low-cut design, ensuring durability and protection against the elements.The waterproof upper is draped in soft tones of \"Cream II\" and \"Light Orewood Brown,\" delivering a neutral aesthetic that seamlessly transitions into everyday lifestyle rotations. Contrast is purposefully introduced through stark black Swooshes and a dark brown collar lining, while delicate gold accents on the tongue branding, pull tabs, and Swoosh stitching elevate the rugged finish. A speckled \"Coconut Milk\" midsole paired with a ru",
   "image": "https://image-cdn.hypb.st/https%3A%2F%2Fhypebeast.com%2Fimage%2F2026%2F09%2F08%2Fair-jordan-1-low-element-gtx-cream-ii-light-orewood-brown-coconut-milk-ridgerock-fv4227-202-official-images-info-0.jpg?w=800&cbr=1&q=90&fit=max",
   "link": "https://hypebeast.com/2026/9/air-jordan-1-low-element-gtx-cream-ii-light-orewood-brown-coconut-milk-ridgerock-fv4227-202-official-images-info",
   "lang": "en",
   "relatedBrands": [
    "JORDAN",
    "UGG"
   ]
  },
  {
   "id": 37,
   "title": "Official Look at the sunlovetour x New Balance Minimus Sneakers",
   "source": "Hypebeast",
   "date": "2026-09-08",
   "content": "Name: sunlovetour x New Balance Minimus MT10 & MT2Colorway: TBCSKU: MT10O1ND, MT298HMSRP: TBCRelease Date: September 11Where to Buy: sunlovetourContinuing their efforts to redefine traditional golf culture through a distinct lifestyle lens, Seoul-based casualwear imprint sunlove has reunited with New Balance for an all-new capsule titled \"SOFT UTILITY : MINIMUS.\" Following the success of their previous collaborative efforts, this sophomore joint venture taps New Balance's iconic barefoot-feel runner - the Minimus - as its foundation.Arriving in two distinct, season-ready colorways characterized by sharp material blocking, the MT10 sneaker features a classic upper constructed from rich suede and breathable mesh in a burgundy red hue -- striking an unexpected visual balance with its contrasting icy blue laces. Joining the lineup is the MT2 model, which arrives as a mary-jane-esque built. T",
   "image": "https://image-cdn.hypb.st/https%3A%2F%2Fhypebeast.com%2Fimage%2F2026%2F09%2F08%2Fsunlovetour-new-balance-soft-utility-collaboration-release-info-0.jpg?w=800&cbr=1&q=90&fit=max",
   "link": "https://hypebeast.com/2026/9/sunlovetour-new-balance-soft-utility-collaboration-release-info",
   "lang": "en",
   "relatedBrands": [
    "NEW BALANCE"
   ]
  },
  {
   "id": 38,
   "title": "Air Jordan 3 TD Football Cleats “Metallic Silver” September 2026 Release Date & Info",
   "source": "Nice Kicks",
   "date": "2026-09-08",
   "content": "Jordan Brand is bringing some shine to the gridiron with a new Air Jordan 3 Football Cleat. The performance-ready take… The post Air Jordan 3 TD Football Cleats “Metallic Silver” September 2026 Release Date & Info appeared first on Nice Kicks .",
   "image": "https://www.nicekicks.com/files/2026/08/imgi_12_JORDAN3MIDTD-e1787851398440.jpeg",
   "link": "https://www.nicekicks.com/air-jordan-3-td-football-cleats-metallic-silver-fz8626-002/",
   "lang": "en",
   "relatedBrands": [
    "JORDAN"
   ]
  },
  {
   "id": 39,
   "title": "Vans Old Skool 36 “Yacht Club”",
   "source": "Nice Kicks",
   "date": "2026-09-08",
   "content": "The Vans Old Skool 36 “Yacht Club” is releasing on September 10, 2026 via Vans and select retailers for $130.… The post Vans Old Skool 36 “Yacht Club” appeared first on Nice Kicks .",
   "image": "https://www.nicekicks.com/files/2026/09/imgi_1_Premium-Old-Skool-36-Shoe-VANS-Green-Red-Blue-Yellow-ALT5-1-e1788542388274.jpeg",
   "link": "https://www.nicekicks.com/vans-old-skool-36-yacht-club-vn000e8vbgk-2026/",
   "lang": "en",
   "relatedBrands": [
    "VANS"
   ]
  }
 ]
};
